### ISSUE TITLE
Make compatible with .NET core

### ISSUE THREAD

**Issue by ErikSvaleng** [provegard/NSpecInNUnit#2]
I'm currently working on a .NET core project, and our team likes NSpec. But I'm having a hard time running the tests with reSharper and when installing NSpecInNUnit VS complains that it's not compatible with .NET core.

**Comment by provegard** [comment]
I'll look into it, after #3.

**Comment by provegard** [comment]
I've been trying to get this to work but I ran into a bug in NUnit 3 when netstandard 1.6 is targeted:

https://github.com/nunit/nunit/issues/2052

Until that bug is fixed, I don't think it's possible to move forward with this issue.

**Comment by provegard** [comment]
Update: It seems as if the bug will be fixed in NUnit 3.7...

**Comment by danrien** [comment]
NUnit is now compatible with .Net Core - have you worked on converting this to .Net core lately?

**Comment by provegard** [comment]
I did try to make it target both core and regular net, but something didn't work - don't recall the details. I'll check again, but I won't have the time the coming two weeks.

**Comment by danrien** [comment]
It should hopefully be straight-forward if you reference the lowest common denominator .Net standard of the two projects. I can try to put up a PR if that would be helpful?

**Comment by provegard** [comment]
Sure, go ahead! :-)

**Comment by danrien** [comment]
Should this issue be closed @provegard?

**Comment by provegard** [comment]
Yes, thanks for noticing!
